### ISSUE TITLE
Transport is broken in laravel 7

### ISSUE THREAD

**Issue by SiebeVE** [SynergiTech/laravel-postal#16]
In Laravel 7 the TransportManager was removed in favor of the new MailManager.
This breaks transport because postal isn't registered.
This can be fixed by using the MailManager instead of the TransportManager in the PostalServiceProvider.

**Comment by willpower232** [comment]
Thanks for letting us know. We don't have any Laravel 7 in the works at the minute, are you able to make a PR with the necessary changes?

**Comment by SiebeVE** [comment]
Even better, I will write 2!
1: disable laravel 7 for current package
2: package for laravel 7.

This way you can tag a package that will still work for current installs and a new major release for laravel 7.

**Comment by willpower232** [comment]
Much obliged!

**Comment by SiebeVE** [comment]
Both pull requests are ready!

**Comment by willpower232** [comment]
Brilliant, thank you.

They look great, mostly just a class name change right? Is there any official documentation on the change we should also refer to?

**Comment by SiebeVE** [comment]
It is a bit more complicated. In Laravel 7 you can use multiple mailers!
The commit where it was removed: https://github.com/laravel/framework/commit/53f555a74cf3d02715b1a4bf7c2a4ac125beab13#diff-025006b2c4889f2136ad802e7ee2f622
And the PR why: https://github.com/laravel/framework/pull/31073

**Comment by RamonSmit** [comment]
The changes are looking good to me, I had to fallback to SMTP for mailing for now, because of the breaking changes in Laravel 7. I can't wait till this get merged, thanks @SiebeVE! 👍

**Comment by willpower232** [comment]
Thanks for all the help, the support for Laravel 7 has been merged and released as version 3.
