### ISSUE TITLE
v2 breaks due to missing `updated_at` column

### ISSUE THREAD

**Issue by a47ae** [SynergiTech/laravel-postal#6]
Hey,
first thank you for your packet.

Sadly when I was evaluating it I ran into the following error:
`Illuminate\Database\QueryException: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "updated_at" of relation "emails" does not exist`.

The error occurs from https://github.com/SynergiTech/laravel-postal/blob/master/src/PostalTransport.php#L198 where the `save` method on the Email model is called which tries to set the `updated_at` timestamp.

To prevent this issue it should be enough to add `const UPDATED_AT = null;` to the Email model to tell Laravel to not use the `updated_at` field.

**Comment by Josh-G** [comment]
Hi @a47ae, that was an oversight on our part. We've now released [v2.0.1](https://github.com/SynergiTech/laravel-postal/releases/tag/v2.0.1) which resolves this issue.
